name: gas_safety_app
description: "A complete Flutter mobile application for a Fire & Gas Safety Alert System using Firebase Realtime Database."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Core and Database
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0

  # State Management
  provider: ^6.1.2

  # Alerts and Notifications
  flutter_local_notifications: ^17.1.2
  vibration: ^3.1.8

  # Network Status
  connectivity_plus: ^6.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
